### ISSUE TITLE
Allow specifying certificate file names

### ISSUE THREAD

**Issue by hayley-jean** [EventStore/es-gencert-cli#15]
Allow specifying the file names of the certificates being generated by the cli.

Additionally, the cli currently crashes if the destination folder already exists. This is a pretty bad user experience if you just want to output a number of certificates to the same folder.

Instead, the cli should just create the new certs in the provided output folder.
@alexeyzimarev should the cli overwrite existing certs if they have the same name, or should that be an option?

<sub>[DEV-78](https://linear.app/eventstore/issue/DEV-78/allow-specifying-certificate-file-names)</sub>

**Comment by yehohanan7** [comment]
right now the behaviour is that we give a very clear error message: `output directory: ./node1 already exists. please delete it and try again`

I think this is a better approach instead of overriding an existing certificate to avoid a user overriding certificates by mistake, wdyt?

**Comment by hayley-jean** [comment]
I actually think that the root of this issue is that you can't specify the name of the certificate and key you are creating.
If you could do so, then you could write the certificates to the same directory without problem unless a certificate with the same name already exists in that directory.

**Comment by alexeyzimarev** [comment]
The behaviour and diagnostic messages are all clear, but it doesn't improve the fact that in many cases all you want is to run a script and then, for example, create a Kubernetes secret from the whole directory. Right now, it's not an easy task, and the amount of steps required to make it all work (including cleanup) is too much.

Protection of the root certificate file is not related to the crash if the *directory* already exists. There's no reason to deny using one directory for all the certificates.
