### ISSUE TITLE
Add validation command

### ISSUE THREAD

**Issue by thomastoye** [EventStore/es-gencert-cli#6]
```
As an inexperienced EventStore user
I want to verify the certificates I generated with es-gent-cli and deployed to my node are set up correctly
So I can validate I followed the instructions correctly 
```

I'm not sure if `es-gencert-cli` is the right place for this, but I'd like to have some kind of validator so I know I deployed the correct certs to the right nodes, that they are reachable, that the SAN matches the domain, etc.

<sub>[DEV-80](https://linear.app/eventstore/issue/DEV-80/add-validation-command)</sub>

**Comment by alexeyzimarev** [comment]
I don't think the certificate generation tool should do such validation. If you use the tool, it will generate correct certificates. If you use the configurator in the docs, it will give you correct cert gen commands and correct configs.
